language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: rbx-19mode
notifications:
  email:
    - dan.kubb@gmail.com
