language: ruby
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci:metrics"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.3
  - ruby-head
  - rbx-2
matrix:
  include: []
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby
      env: JRUBY_OPTS="$JRUBY_OPTS --debug --1.9"  # for simplecov
    - rvm: jruby
      env: JRUBY_OPTS="$JRUBY_OPTS --debug --2.0"  # for simplecov
  fast_finish: true
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
